### ISSUE TITLE
name,     checkIn,  checkOut 넘어가지않고 있음

### ISSUE THREAD

**Issue by 0hu** [CodeSoom-Project/my-seat#30]
name, checkIn, checkOut 전송시 null로 전송됨

**Comment by JIY0UNG** [comment]
@0hu 이제 checkIn과  checkOut은 정상적인 값이 들어오는데, name은 아직 null로 들어오네요! 확인 한번 부탁드려요

**Comment by 0hu** [comment]
전달 완료
이슈 종료하겠습니다.
