### ISSUE TITLE
app-web 프로젝트 빌드 실패

### ISSUE THREAD

**Issue by JIY0UNG** [CodeSoom-Project/my-seat#62]
## 버그 설명
- `npm run build` 명령어 실행 시 아래와 같은 로그와 함께 빌드에 실패합니다.

## 로그
```bash
src/App.tsx:11:8 - error TS2786: 'ReservationListContainer' cannot be used as a JSX component.  Its return type 'Element | "예약 정보를 불러오는중입니다." | "무언가 잘 못 돼었습니다."' is 
not a valid JSX element.
    Type 'string' is not assignable to type 'ReactElement<any, any>'.

11       <ReservationListContainer />
          ~~~~~~~~~~~~~~~~~~~~~~~~

src/ReservationSlice.ts:16:5 - error TS2322: Type 'string' is not assignable to type 'number'.
16     seatNumber: '',
       ~~~~~~~~~~

  src/ReservationSlice.ts:4:3
    4   seatNumber: number;
        ~~~~~~~~~~
    The expected type comes from property 'seatNumber' which is declared here on type 'ReservationState'


Found 2 errors in 2 files.

Errors  Files
     1  src/App.tsx:11
     1  src/ReservationSlice.ts:16
```

**Comment by 0hu** [comment]
`
transforming (259) node_modules\@babel\runtime\helpers\esm\setPrototypeOf.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
'getDefaultExportFromCjs' is not exported by 'commonjsHelpers.js'
✓ 265 modules transformed.
'getAugmentedNamespace' is not exported by commonjsHelpers.js, imported by react/jsx-runtime?commonjs-proxy
file: react/jsx-runtime?commonjs-proxy:1:57
1: import * as jsxRuntime from "react/jsx-runtime"; import {getAugmentedNamespace} from "commonjsHelpers.js"; export default /*@__PURE__*/getAugmentedNamespace(jsxRuntime);
                                                            ^
error during build:
Error: 'getAugmentedNamespace' is not exported by commonjsHelpers.js, imported by react/jsx-runtime?commonjs-proxy

`

**Comment by 0hu** [comment]
빌드 완료 issue 끝내겠습니다.
